# Generated by Django 5.2.17 on 2026-08-21 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcrianca',
            name='acesso_proprio',
            field=models.BooleanField(default=False, verbose_name='Acesso pelo próprio celular'),
        ),
        migrations.AddField(
            model_name='perfilcrianca',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nome da criança'),
        ),
        migrations.AlterField(
            model_name='perfilcrianca',
            name='usuario',
            field=models.OneToOneField(blank=True, limit_choices_to={'tipo': 'CRIANCA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_crianca', to=settings.AUTH_USER_MODEL),
        ),
    ]
