# Generated by Django 5.2.17 on 2026-08-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilcrianca_acesso_proprio_perfilcrianca_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilcrianca',
            options={'verbose_name': 'Perfil da criança', 'verbose_name_plural': 'Perfis das crianças'},
        ),
        migrations.AddField(
            model_name='perfilcrianca',
            name='avatar_tipo',
            field=models.CharField(choices=[('ROBO', '🤖 Robô'), ('RAPOSA', '🦊 Raposa'), ('DRAGAO', '🐲 Dragão'), ('NINJA', '🥷 Ninja')], default='ROBO', max_length=20, verbose_name='Avatar'),
        ),
    ]
