# Generated by Django 5.2.17 on 2026-08-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfilcrianca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='boas_vindas_exibidas',
            field=models.BooleanField(default=False, verbose_name='Boas-vindas já exibidas'),
        ),
        migrations.AlterField(
            model_name='perfilcrianca',
            name='avatar_tipo',
            field=models.CharField(choices=[('ROBO', '🤖 Robô'), ('RAPOSA', '🦊 Raposa'), ('DRAGAO', '🐲 Dragão'), ('ASTRONAUTA', '🧑\u200d🚀 Astronauta')], default='ROBO', max_length=20, verbose_name='Avatar'),
        ),
    ]
