from django.db import transaction

from tarefas.models import SugestaoTarefa

from .models import (
    Conquista,
    Skill,
    SugestaoTarefaSkill,
)


SKILLS_PADRAO = [
    (
        "autonomia",
        "Autonomia",
        "🌱",
        "Prática de pequenas atividades com participação cada vez mais independente.",
        10,
    ),
    (
        "organizacao",
        "Organização",
        "📋",
        "Prática de ordenar materiais, espaços e pequenas rotinas.",
        20,
    ),
    (
        "responsabilidade",
        "Responsabilidade",
        "✅",
        "Prática de assumir e concluir pequenas obrigações combinadas.",
        30,
    ),
    (
        "constancia",
        "Constância",
        "🔁",
        "Prática repetida de hábitos e compromissos ao longo do tempo.",
        40,
    ),
    (
        "autocuidado",
        "Autocuidado",
        "🧼",
        "Prática de higiene e cuidados pessoais compatíveis com a idade.",
        50,
    ),
    (
        "foco",
        "Foco",
        "🎯",
        "Prática de permanecer em uma atividade até concluir uma etapa combinada.",
        60,
    ),
    (
        "colaboracao",
        "Colaboração",
        "🤝",
        "Prática de contribuir em atividades compartilhadas com a família.",
        70,
    ),
    (
        "iniciativa",
        "Iniciativa",
        "💡",
        "Prática de começar pequenas ações com menor dependência de lembretes.",
        80,
    ),
]


SUGESTOES_PADRAO = [
    {
        "icone": "🧸",
        "titulo": "Guardar os brinquedos depois de brincar",
        "descricao": "Guardar os brinquedos no local combinado ao terminar de brincar.",
        "categoria": "ORGANIZACAO",
        "idade_minima": 3,
        "idade_maxima": 5,
        "pontos": 5,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 10,
        "skills": {
            "autonomia": 2,
            "organizacao": 2,
            "responsabilidade": 1,
        },
    },
    {
        "icone": "🧺",
        "titulo": "Colocar a roupa suja no cesto",
        "descricao": "Levar a roupa usada até o cesto após trocar de roupa.",
        "categoria": "AUTONOMIA",
        "idade_minima": 3,
        "idade_maxima": 6,
        "pontos": 5,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 20,
        "skills": {
            "autonomia": 2,
            "organizacao": 2,
            "autocuidado": 1,
        },
    },
    {
        "icone": "👟",
        "titulo": "Guardar os sapatos no lugar",
        "descricao": "Colocar os sapatos no local definido após chegar em casa.",
        "categoria": "ORGANIZACAO",
        "idade_minima": 3,
        "idade_maxima": 7,
        "pontos": 5,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 30,
        "skills": {
            "organizacao": 2,
            "autonomia": 1,
        },
    },
    {
        "icone": "🍽️",
        "titulo": "Levar o prato até a pia",
        "descricao": "Depois da refeição, levar prato e talheres até o local combinado.",
        "categoria": "COLABORACAO",
        "idade_minima": 4,
        "idade_maxima": 8,
        "pontos": 5,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 40,
        "skills": {
            "colaboracao": 2,
            "responsabilidade": 2,
            "autonomia": 1,
        },
    },
    {
        "icone": "🪥",
        "titulo": "Escovar os dentes com supervisão",
        "descricao": "Realizar a escovação nos horários combinados com acompanhamento do responsável.",
        "categoria": "AUTOCUIDADO",
        "idade_minima": 3,
        "idade_maxima": 6,
        "pontos": 5,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 50,
        "skills": {
            "autocuidado": 3,
            "constancia": 2,
        },
    },
    {
        "icone": "👕",
        "titulo": "Escolher a roupa com ajuda",
        "descricao": "Participar da escolha da roupa adequada para o dia.",
        "categoria": "AUTONOMIA",
        "idade_minima": 4,
        "idade_maxima": 6,
        "pontos": 5,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 60,
        "skills": {
            "autonomia": 2,
            "iniciativa": 1,
        },
    },
    {
        "icone": "🛏️",
        "titulo": "Arrumar a cama",
        "descricao": "Organizar a cama após acordar.",
        "categoria": "ORGANIZACAO",
        "idade_minima": 6,
        "idade_maxima": 17,
        "pontos": 5,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 70,
        "skills": {
            "autonomia": 3,
            "organizacao": 2,
            "responsabilidade": 1,
        },
    },
    {
        "icone": "🎒",
        "titulo": "Organizar a mochila para a escola",
        "descricao": "Conferir e separar os materiais necessários para o próximo dia.",
        "categoria": "ESTUDOS",
        "idade_minima": 6,
        "idade_maxima": 12,
        "pontos": 10,
        "frequencia": "SEMANAL",
        "dias": "0,1,2,3,4",
        "ordem": 80,
        "skills": {
            "organizacao": 3,
            "responsabilidade": 2,
            "autonomia": 2,
        },
    },
    {
        "icone": "📚",
        "titulo": "Guardar o material escolar após usar",
        "descricao": "Guardar livros, cadernos e objetos no local definido após a atividade.",
        "categoria": "ESTUDOS",
        "idade_minima": 6,
        "idade_maxima": 10,
        "pontos": 5,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 90,
        "skills": {
            "organizacao": 3,
            "responsabilidade": 2,
        },
    },
    {
        "icone": "👚",
        "titulo": "Separar a roupa do dia seguinte",
        "descricao": "Escolher e deixar pronta a roupa que será usada no próximo dia.",
        "categoria": "AUTONOMIA",
        "idade_minima": 7,
        "idade_maxima": 17,
        "pontos": 5,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 100,
        "skills": {
            "autonomia": 3,
            "organizacao": 2,
        },
    },
    {
        "icone": "🍴",
        "titulo": "Ajudar a colocar a mesa",
        "descricao": "Participar da organização da mesa antes de uma refeição.",
        "categoria": "COLABORACAO",
        "idade_minima": 6,
        "idade_maxima": 11,
        "pontos": 10,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 110,
        "skills": {
            "colaboracao": 3,
            "responsabilidade": 2,
        },
    },
    {
        "icone": "🧼",
        "titulo": "Conferir a higiene antes de dormir",
        "descricao": "Conferir escovação, banho ou outros cuidados combinados para a noite.",
        "categoria": "AUTOCUIDADO",
        "idade_minima": 6,
        "idade_maxima": 12,
        "pontos": 5,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 120,
        "skills": {
            "autocuidado": 3,
            "constancia": 2,
            "responsabilidade": 1,
        },
    },
    {
        "icone": "🗂️",
        "titulo": "Organizar o espaço de estudo",
        "descricao": "Deixar mesa, materiais e ambiente de estudo organizados antes ou depois de estudar.",
        "categoria": "ESTUDOS",
        "idade_minima": 9,
        "idade_maxima": 17,
        "pontos": 10,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 130,
        "skills": {
            "organizacao": 3,
            "foco": 2,
            "responsabilidade": 1,
        },
    },
    {
        "icone": "📖",
        "titulo": "Fazer um bloco de leitura ou estudo",
        "descricao": "Cumprir o período de leitura ou estudo combinado com o responsável.",
        "categoria": "ESTUDOS",
        "idade_minima": 8,
        "idade_maxima": 17,
        "pontos": 10,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 140,
        "skills": {
            "foco": 3,
            "constancia": 2,
            "responsabilidade": 1,
        },
    },
    {
        "icone": "🧹",
        "titulo": "Ajudar em uma tarefa doméstica combinada",
        "descricao": "Realizar uma pequena responsabilidade doméstica adequada à idade.",
        "categoria": "CASA",
        "idade_minima": 8,
        "idade_maxima": 17,
        "pontos": 10,
        "frequencia": "SEMANAL",
        "dias": "5",
        "ordem": 150,
        "skills": {
            "colaboracao": 3,
            "responsabilidade": 3,
            "autonomia": 1,
        },
    },
    {
        "icone": "🥪",
        "titulo": "Preparar um lanche simples com supervisão",
        "descricao": "Participar do preparo de um lanche simples e organizar o local depois.",
        "categoria": "AUTONOMIA",
        "idade_minima": 9,
        "idade_maxima": 13,
        "pontos": 10,
        "frequencia": "SEMANAL",
        "dias": "5,6",
        "ordem": 160,
        "skills": {
            "autonomia": 3,
            "iniciativa": 2,
            "organizacao": 1,
        },
    },
    {
        "icone": "📝",
        "titulo": "Planejar as tarefas escolares do dia",
        "descricao": "Listar o que precisa ser feito e definir uma ordem para começar.",
        "categoria": "ESTUDOS",
        "idade_minima": 11,
        "idade_maxima": 17,
        "pontos": 10,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 170,
        "skills": {
            "organizacao": 3,
            "responsabilidade": 2,
            "foco": 2,
        },
    },
    {
        "icone": "🛏️",
        "titulo": "Manter o quarto organizado",
        "descricao": "Fazer uma organização breve do quarto, guardando itens fora do lugar.",
        "categoria": "ORGANIZACAO",
        "idade_minima": 10,
        "idade_maxima": 17,
        "pontos": 10,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 180,
        "skills": {
            "organizacao": 3,
            "responsabilidade": 2,
            "constancia": 2,
        },
    },
    {
        "icone": "🎒",
        "titulo": "Preparar os materiais para o dia seguinte",
        "descricao": "Separar materiais escolares, itens pessoais e o que será necessário no próximo dia.",
        "categoria": "ORGANIZACAO",
        "idade_minima": 11,
        "idade_maxima": 17,
        "pontos": 10,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 190,
        "skills": {
            "organizacao": 3,
            "autonomia": 3,
            "responsabilidade": 2,
        },
    },
    {
        "icone": "🎯",
        "titulo": "Fazer um período de estudo sem distrações",
        "descricao": "Realizar o período de estudo combinado evitando interrupções desnecessárias.",
        "categoria": "ESTUDOS",
        "idade_minima": 12,
        "idade_maxima": 17,
        "pontos": 15,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 200,
        "skills": {
            "foco": 3,
            "constancia": 2,
            "responsabilidade": 1,
        },
    },
    {
        "icone": "🏠",
        "titulo": "Participar de uma responsabilidade da casa",
        "descricao": "Cumprir uma responsabilidade doméstica definida em conjunto com a família.",
        "categoria": "CASA",
        "idade_minima": 12,
        "idade_maxima": 17,
        "pontos": 15,
        "frequencia": "SEMANAL",
        "dias": "5",
        "ordem": 210,
        "skills": {
            "colaboracao": 3,
            "responsabilidade": 3,
            "autonomia": 2,
        },
    },
    {
        "icone": "📅",
        "titulo": "Organizar os compromissos da semana",
        "descricao": "Revisar compromissos, atividades escolares e tarefas previstas para a semana.",
        "categoria": "ORGANIZACAO",
        "idade_minima": 13,
        "idade_maxima": 17,
        "pontos": 15,
        "frequencia": "SEMANAL",
        "dias": "6",
        "ordem": 220,
        "skills": {
            "organizacao": 3,
            "autonomia": 3,
            "iniciativa": 2,
        },
    },
    {
        "icone": "📦",
        "titulo": "Guardar os objetos depois de usar",
        "descricao": "Devolver objetos e materiais ao lugar combinado ao terminar de usá-los.",
        "categoria": "ORGANIZACAO",
        "idade_minima": 4,
        "idade_maxima": 17,
        "pontos": 5,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 230,
        "skills": {
            "organizacao": 2,
            "responsabilidade": 2,
        },
    },
    {
        "icone": "🌙",
        "titulo": "Preparar-se para dormir no horário combinado",
        "descricao": "Iniciar a rotina noturna e estar pronto para dormir no horário acordado.",
        "categoria": "AUTOCUIDADO",
        "idade_minima": 5,
        "idade_maxima": 17,
        "pontos": 5,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 240,
        "skills": {
            "constancia": 3,
            "responsabilidade": 2,
            "autocuidado": 2,
        },
    },
    {
        "icone": "🎒",
        "titulo": "Cuidar dos próprios pertences",
        "descricao": "Conferir e guardar os próprios itens no lugar adequado.",
        "categoria": "AUTONOMIA",
        "idade_minima": 5,
        "idade_maxima": 17,
        "pontos": 5,
        "frequencia": "DIARIA",
        "dias": "",
        "ordem": 250,
        "skills": {
            "autonomia": 3,
            "responsabilidade": 2,
            "organizacao": 1,
        },
    },
]


CONQUISTAS_PADRAO = [
    {
        "slug": "primeira-missao",
        "nome": "Primeiros Passos",
        "icone": "🌟",
        "descricao": "Concluir e ter a primeira tarefa aprovada.",
        "ordem": 10,
    },
    {
        "slug": "dez-missoes",
        "nome": "Em Ritmo",
        "icone": "🎯",
        "descricao": "Alcançar 10 tarefas aprovadas.",
        "ordem": 20,
    },
    {
        "slug": "trinta-missoes",
        "nome": "Super Rotina",
        "icone": "🏆",
        "descricao": "Alcançar 30 tarefas aprovadas.",
        "ordem": 30,
    },
    {
        "slug": "sequencia-sete",
        "nome": "Constante",
        "icone": "🔥",
        "descricao": "Cumprir 7 dias de rotina em sequência.",
        "ordem": 40,
    },
    {
        "slug": "autonomia-n3",
        "nome": "Mais Independente",
        "icone": "🌱",
        "descricao": "Chegar ao nível 3 de Autonomia.",
        "ordem": 50,
    },
    {
        "slug": "organizacao-n3",
        "nome": "Superorganizado",
        "icone": "📋",
        "descricao": "Chegar ao nível 3 de Organização.",
        "ordem": 60,
    },
]


@transaction.atomic
def carregar_catalogo_padrao(
    sender=None,
    **kwargs,
):
    for item in CONQUISTAS_PADRAO:
        Conquista.objects.update_or_create(
            slug=item["slug"],
            defaults={
                "nome": item["nome"],
                "icone": item["icone"],
                "descricao": item["descricao"],
                "ordem": item["ordem"],
                "ativa": True,
            },
        )

    skills = {}

    for (
        slug,
        nome,
        icone,
        descricao,
        ordem,
    ) in SKILLS_PADRAO:
        skill, _ = Skill.objects.update_or_create(
            slug=slug,
            defaults={
                "nome": nome,
                "icone": icone,
                "descricao": descricao,
                "ordem": ordem,
                "ativa": True,
            },
        )
        skills[slug] = skill

    for item in SUGESTOES_PADRAO:
        sugestao, _ = SugestaoTarefa.objects.update_or_create(
            titulo=item["titulo"],
            defaults={
                "icone": item.get(
                    "icone",
                    "✨",
                ),
                "descricao": item["descricao"],
                "categoria": item["categoria"],
                "idade_minima": item["idade_minima"],
                "idade_maxima": item["idade_maxima"],
                "pontos_sugeridos": item["pontos"],
                "frequencia_sugerida": item["frequencia"],
                "dias_semana": item["dias"],
                "ativa": True,
                "ordem": item["ordem"],
            },
        )

        SugestaoTarefaSkill.objects.filter(
            sugestao=sugestao
        ).delete()

        for slug, impacto in item["skills"].items():
            SugestaoTarefaSkill.objects.create(
                sugestao=sugestao,
                skill=skills[slug],
                impacto=impacto,
            )
